# Zomato Orders Analysis

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_orders = pd.read_csv('/Volumes/Media/github file/zomato_orders_data /data/orders_table.csv')
df_customers = pd.read_csv('/Volumes/Media/github file/zomato_orders_data /data/customers.csv')
df_restaurants = pd.read_csv('/Volumes/Media/github file/zomato_orders_data /data/restaurant_table.csv')

df_customers
# df_orders
# df_restaurants

     Customer_id   Customer_name       City Signup_Time Acquisition_channel
0          C00002  Rohan Agarwal      Delhi  2024-05-06             Organic
1          C00003    Priya Verma  Hyderabad  2025-10-13       Instagram Ads
2          C00004     Neha Singh     Mumbai  2024-02-06   WhatsApp Campaign
3          C00005     Amit Kumar      Noida  2024-11-08            Referral
4          C00006  Rohan Agarwal    Chennai  2024-06-04       Instagram Ads
...           ...            ...        ...         ...                 ...
4994       C04996    Priya Verma    Chennai  2024-11-07          Google Ads
4995       C04997   Rahul Sharma      Noida  2025-10-18          Google Ads
4996       C04998  Rohan Agarwal      Delhi  2025-06-21       Instagram Ads
4997       C04999     Amit Kumar  Bengaluru  2024-05-15   WhatsApp Campaign
4998       C05000     Amit Kumar      Noida  2025-11-05       Instagram Ads

[4999 rows x 5 columns]

In [5]:
df_orders.shape
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49990 entries, 0 to 49989
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         49990 non-null  object
 1   customer_id      49990 non-null  object
 2   restaurant_id    49990 non-null  object
 3   order_timestamp  49990 non-null  object
 4   order_amount     49990 non-null  float64
 5   discount_amount  49990 non-null  float64
 6   delivery_fee     49990 non-null  int64
 7   payment_mode     49990 non-null  object
 8   order_status     49990 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 3.4+ MB

In [7]:
print(df_orders.columns.tolist())
print(df_customers.columns.tolist())

['order_id', 'customer_id', 'restaurant_id', 'order_timestamp', 'order_amount', 'discount_amount', 'delivery_fee', 'payment_mode', 'order_status']
['Customer_id ', 'Customer_name', 'City', 'Signup_Time', 'Acquisition_channel']

In [13]:
df_orders.columns = df_orders.columns.str.strip()
df_customers.columns = df_customers.columns.str.strip()

### rename columns name from custoemrs table

In [16]:
df_customers.rename(columns = {"Customer_id": "customer_id",
                            "Customer_name": "customer_name",
                            "City": "city",
                            "Signup_Time": "signup_time",
                            "Acquisition_channel": "acquisition_channel"}, inplace = True)

In [17]:
df_customers.columns

Index(['customer_id', 'customer_name', 'city', 'signup_time',
       'acquisition_channel'],
      dtype='object')

## Merge all  Tables with left join

In [18]:
df = (df_orders.merge(df_customers, on="customer_id", how="left")
        .merge(df_restaurants, on="restaurant_id", how="left"))
df

,order_id,customer_id,restaurant_id,order_timestamp,order_amount,discount_amount,delivery_fee,payment_mode,order_status,customer_name,city_x,signup_time,acquisition_channel,restaurant_name,cuisine,city_y,avg_rating
0,O000001,C03175,R0115,2025-09-28,1079.36,107.94,39,Cash,Refunded,Rohan Agarwal,Bengaluru,2024-06-26,Instagram Ads,Burger King,Biryani,Gurugram,4.9
1,O000002,C02432,R0077,2024-02-13,1499.63,149.96,42,Card,Delivered,Rohan Agarwal,Delhi,2025-11-06,Instagram Ads,Biryani By Kilo,Pizza,Hyderabad,4.0
2,O000003,C01133,R0131,2024-03-07,597.18,59.72,22,Cash,Delivered,Priya Verma,Chennai,2024-01-26,Referral,KFC,Fast Food,Delhi,3.8
3,O000004,C04813,R0109,2025-01-27,1257.48,125.75,53,Wallet,Delivered,Amit Kumar,Pune,2024-08-22,Organic,Pizza Hut,Healthy,Chennai,3.9
4,O000005,C04948,R0001,2024-10-25,1010.57,0.00,28,Wallet,Delivered,Neha Singh,Hyderabad,2025-09-12,WhatsApp Campaign,Chaayos,Fast Food,Hyderabad,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49985,O049996,C00335,R0027,2024-11-02,368.31,0.00,53,Cash,Delivered,Neha Singh,Pune,2025-03-04,Google Ads,KFC,Fast Food,Pune,4.2
49986,O049997,C00461,R0139,2025-06-14,560.93,56.09,28,UPI,Delivered,Rohan Agarwal,Pune,2024-05-23,Google Ads,McDonald's,North Indian,Bengaluru,4.9
49987,O049998,C00019,R0022,2025-06-24,891.67,0.00,29,Cash,Refunded,Amit Kumar,Pune,2025-11-15,Instagram Ads,Behrouz Biryani,North Indian,Chennai,3.9
49988,O049999,C00235,R0107,2025-09-13,704.99,0.00,54,Card,Refunded,Rohan Agarwal,Hyderabad,2024-09-16,WhatsApp Campaign,KFC,North Indian,Bengaluru,4.2
49989,O050000,C00631,R0179,2025-05-25,1103.95,0.00,22,UPI,Delivered,Neha Singh,Chennai,2024-07-11,WhatsApp Campaign,Subway,Cafe,Delhi,4.3

# Data Analyst

## Zomato Revenue Analysis

In [75]:
# 1. What is the total revenue?
revenue= df['order_amount'].sum()
print(f"Total Revenue: {revenue}")

Total Revenue: 44947492.74

In [179]:
#2. What is the monthly revenue trend?
df['order_timestamp']= pd.to_datetime(df['order_timestamp'])
df['month'] = df['order_timestamp'].dt.to_period('M')
print(df.groupby('month')['order_amount'].sum().reset_index())

      month  order_amount
0   2024-01    1644729.63
1   2024-02    1547337.20
2   2024-03    1625528.40
3   2024-04    1653283.91
4   2024-05    1593857.14
5   2024-06    1593303.58
6   2024-07    1572871.10
7   2024-08    1642355.70
8   2024-09    1565960.57
9   2024-10    1664510.98
10  2024-11    1602030.93
11  2024-12    1610403.62
12  2025-01    1699375.92
13  2025-02    1465083.41
14  2025-03    1617972.16
15  2025-04    1522883.42
16  2025-05    1652169.37
17  2025-06    1579773.03
18  2025-07    1623827.14
19  2025-08    1580881.69
20  2025-09    1580452.89
21  2025-10    1704383.33
22  2025-11    1601460.28
23  2025-12    1702655.78
24  2026-01    1632463.33
25  2026-02    1517011.26
26  2026-03    1609189.09
27  2026-04    1541737.88

In [177]:
#3. Which city contributes the highest revenue?

city_revenue= df.groupby('city_y')['order_amount'].sum().sort_values(ascending=False).reset_index()
city_revenue

      city_y  order_amount
0    Chennai    7265344.91
1       Pune    6113580.86
2  Hyderabad    5973716.15
3      Noida    5876795.10
4      Delhi    5824124.24
5   Gurugram    4944961.91
6     Mumbai    4490993.27
7  Bengaluru    4457976.30

In [176]:
#4. Which payment mode generates the most revenue?
payment_revenue =df.groupby('payment_mode')['order_amount'].sum().sort_values(ascending=False).reset_index()
payment_revenue

  payment_mode  order_amount
0          UPI   22407784.43
1       Wallet    7549550.36
2         Cash    7499747.57
3         Card    7490410.38

In [169]:
#5. What is the Average Order Value (AOV)?
Aov = df['order_amount'].mean()
print(f"Average Order value: {Aov:.2f}")

Average Order value: 899.13

## Customer Analysis

In [189]:
#1. Who are the top 10 customers by revenue?\
customer_revenue =df.groupby(['customer_name', 'customer_id'])['order_amount'].sum().sort_values(ascending=False).head(10).reset_index()
customer_revenue

   customer_name customer_id  order_amount
0     Amit Kumar      C04598      21549.15
1    Arjun Gupta      C02951      20944.01
2  Ananya Mishra      C00681      20249.97
3  Ananya Mishra      C00381      20192.06
4     Neha Singh      C04768      19882.52
5     Neha Singh      C01659      19316.98
6   Rahul Sharma      C03377      19284.45
7    Priya Verma      C00701      19174.04
8    Priya Verma      C04613      19053.09
9  Ananya Mishra      C01140      19034.23

In [209]:
# 2. What percentage of revenue comes from top customers?
df['customer_revenue'] = df.groupby('customer_id')['order_amount'].transform('sum')
top_customers_revenue = df[df['customer_revenue'] > df['customer_revenue'].quantile(0.9)]['order_amount'].sum()
total_revenue = df['order_amount'].sum()
percentage_top_customers = (top_customers_revenue / total_revenue) * 100
print(f"Percentage of revenue from top customers: {percentage_top_customers:.2f}%")

Percentage of revenue from top customers: 10.80%

In [217]:
# 3. Which acquisition channel brings the highest-value customers?
df['customer_value'] = df.groupby('customer_id')['order_amount'].transform('sum')
acquisition_channel_value = df.groupby('acquisition_channel')['customer_value'].sum()
highest_value_channel = acquisition_channel_value.idxmax()
print(f"Acquisition channel with highest-value customers: {highest_value_channel}")

Acquisition channel with highest-value customers: Instagram Ads

In [232]:
# 4. How many repeat customers do we have?
df['customer_order_count'] = df.groupby('customer_id')['order_id'].transform('count')
repeat_customers_count = df[df['customer_order_count'] > 1]['customer_id'].nunique()
print(f"Number of repeat customers: {repeat_customers_count}")

Number of repeat customers: 4997

## Restaurant Performance

In [270]:
# 1. Which restaurants generate the highest revenue?
restuarant_revenues = df.groupby("restaurant_name")['order_amount'].sum().sort_values(ascending=False).reset_index(name='total_revenue')
restuarant_revenues

    restaurant_name  total_revenue
0   Barbeque Nation     4542995.70
1       Burger King     4514986.93
2   Biryani By Kilo     4273161.69
3           Chaayos     4272047.92
4   Behrouz Biryani     4226769.96
5        Haldiram's     4110222.26
6    Domino's Pizza     3952800.44
7         Starbucks     3558253.66
8               KFC     3437112.72
9        McDonald's     2919913.43
10        Pizza Hut     2892713.95
11           Subway     2246514.08

In [242]:
# 2. Which restaurants receive the most orders?
restaurant_orders = df.groupby("restaurant_name")['order_id'].count().sort_values(ascending=False)
restaurant_orders

restaurant_name
Barbeque Nation    5034
Burger King        5026
Biryani By Kilo    4793
Chaayos            4731
Behrouz Biryani    4656
Haldiram's         4561
Domino's Pizza     4394
Starbucks          3970
KFC                3791
McDonald's         3291
Pizza Hut          3235
Subway             2508
Name: order_id, dtype: int64

In [ ]:
# 3. Which cuisines are most popular?
cuisine_orders = df.groupby('cuisine')['order_id'].count().sort_values(ascending=False).reset_index()
cuisine_orders

        cuisine  order_id
0  North Indian      9807
1         Pizza      9456
2     Fast Food      9147
3       Healthy      7580
4          Cafe      7567
5       Biryani      6433

In [261]:
# 4. Do highly-rated restaurants generate more revenue?
highly_rated_revenue = df.groupby('restaurant_name').agg({'avg_rating': 'mean', 'order_amount': 'sum' }).sort_values(by='avg_rating', ascending=False).head(3).reset_index()
highly_rated_revenue

   restaurant_name  avg_rating  order_amount
0       Haldiram's    4.420631    4110222.26
1   Domino's Pizza    4.372849    3952800.44
2  Barbeque Nation    4.345908    4542995.70

In [19]:
# 5. Last 5 Restaurants
last_5_restaurants = df.groupby('restaurant_name').size().sort_values(ascending=False).tail(5).reset_index(name='order_count')
last_5_restaurants

  restaurant_name  order_count
0       Starbucks         3970
1             KFC         3791
2      McDonald's         3291
3       Pizza Hut         3235
4          Subway         2508

## Coupon Analysis

In [53]:
# A coupon is considered used when discount_amount is >0
df['coupon_used']= df['discount_amount']>0
df['coupon_used']

0         True
1         True
2         True
3         True
4        False
         ...
49985    False
49986     True
49987    False
49988    False
49989    False
Name: coupon_used, Length: 49990, dtype: bool

In [54]:
# 1. What percentage of orders use coupons?
coupon_precentage = df['coupon_used'].mean() *100
print(f"coupon_percentage: {coupon_precentage:.2f}% of orders used coupon")

coupon_percentage: 40.26% of orders used coupon

In [55]:

# 2. Do coupon users spend more than non-coupon users?
spending_comparision = (
    df.groupby('coupon_used')['order_amount']
    .agg(
        Total_orders = 'count',
        avg_order_amount = 'mean',
        Total_spending= 'sum'
    )
    .reset_index()
)
spending_comparision['customer_type'] = (
    spending_comparision['coupon_used']
    .map(
        {True : 'coupon users',
        False : "non_coupon_users"})
)
spending_comparision

,coupon_used,Total_orders,avg_order_amount,Total_spending,customer_type
0,False,29864,897.786900,26811507.99,non_coupon_users
1,True,20126,901.122168,18135984.75,coupon users

In [56]:
# 3. Which city uses the most coupons?
coupon_by_city = (
    df[df['coupon_used']]
    .groupby('city_y')
    .size()
    .sort_values(ascending =False)
    .reset_index(name= 'coupon_orders')

)
coupon_by_city

      city_y  coupon_orders
0    Chennai           3311
1       Pune           2720
2  Hyderabad           2646
3      Noida           2632
4      Delhi           2615
5   Gurugram           2163
6  Bengaluru           2033
7     Mumbai           2006

In [57]:

# 4. Are coupons helping customer retention?

df['order_timestamp'] = pd.to_datetime(df['order_timestamp'])

customer_orders = df.sort_values(
    ['customer_id','order_timestamp']
)
customer_retention = (
    customer_orders.groupby('customer_id')
    .agg(
        total_orders = ('order_id' , 'count'),
        first_order_coupon = ('coupon_used','first')
    )
    .reset_index()

)
customer_retention['retained'] = (
    customer_retention['total_orders']>1

)
retention_comparision = (
    customer_retention.groupby('first_order_coupon')
    .agg(
        total_customers= ('customer_id','count'),
        retained_customers = ('retained' , 'sum'),
        retention_rate = ('retained','mean')
    )
    .reset_index()
)

retention_comparision['retention_rate'] *=100
retention_comparision['customer_type'] =(
    retention_comparision ['first_order_coupon'].map({
        True : 'first_order coupon users',
        False: 'first_order non -coupon users'
    })
)

retention_comparision

,first_order_coupon,total_customers,retained_customers,retention_rate,customer_type
0,False,2963,2963,100.000000,first_order non -coupon users
1,True,2036,2034,99.901768,first_order coupon users

# Cancellation & Refund Analysis

In [ ]:

# 1. What is the cancellation rate?

# 2. What is the refund rate?
# 3. How much revenue is lost due to cancellations?
# 4. Which restaurants have the highest cancellation rate?